### ISSUE TITLE
what difference betwen virgins?

### ISSUE THREAD

**Issue by mte0** [808-Dev/NFT-Miner#3]
can tell difference between the different virgins? (1.0, 1.2, alpha)

**Comment by 808-Dev** [comment]
I really don't know or care. Half of these things are mainly just made up in the middle of the night when I am about to fall asleep.

But yes I can tell the difference. 

Alpha - First one I made and uploaded for shits and giggles.
1.0 - Trying to learn Tweepy API which caused it to lock up from too many API calls.
1.2 - Emergency fix for the bug as well as a few cleaner lines of code? I forgot to be honest.

**Comment by 808-Dev** [comment]
This entire project and most of the projects on my account are supposed to be shitposts.
